/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import javax.swing.SwingUtilities;
import utilerias.HintToTextField;


/**
 *
 * @author Sergio Arturo
 */
public class FrmAdministrarCategorias extends javax.swing.JFrame {

  
    FrmPanelAdministrador admin;
    
    
    /**
     * Creates new form FrmDetallesProductos
     */
    public FrmAdministrarCategorias(FrmPanelAdministrador admin) {
        initComponents();
        
        this.admin = admin;
        
        
        cargarDiseno();
        
    }
    
    
    
    private void cargarDiseno(){
    
        HintToTextField.addHint(txtBuscar, "Buscar Categoria");
        HintToTextField.addHint(txtNombreCategoria, "Nombre de la Categoria");
        
        SwingUtilities.invokeLater(() -> {
            jLabel2.requestFocusInWindow(); // El foco se va al label
        });
        
    }
    
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelEncabezado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelListaCategorias = new javax.swing.JPanel();
        txtBuscar = new javax.swing.JTextField();
        cbInactivas = new javax.swing.JCheckBox();
        jPanelListaCategorias1 = new javax.swing.JPanel();
        txtNombreCategoria = new javax.swing.JTextField();
        btnEliminarCategoria = new javax.swing.JButton();
        btnNuevaCategoria = new javax.swing.JButton();
        btnEditarCategoria = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comanda: Detalles del Producto");
        setMinimumSize(new java.awt.Dimension(1230, 620));
        setPreferredSize(new java.awt.Dimension(1230, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 620));
        getContentPane().setLayout(null);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setMinimumSize(new java.awt.Dimension(1230, 620));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(1230, 620));
        jPanelFondo.setLayout(null);

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEncabezado.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(31, 41, 55));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanelEncabezado.add(jPanel3);
        jPanel3.setBounds(10, 10, 32, 32);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 24, 17));
        jLabel2.setText("Café Express POS: Panel Administrador - Administrar categoria");
        jLabel2.setAlignmentX(16.0F);
        jLabel2.setAlignmentY(0.0F);
        jPanelEncabezado.add(jLabel2);
        jLabel2.setBounds(50, 15, 830, 24);

        jPanelFondo.add(jPanelEncabezado);
        jPanelEncabezado.setBounds(0, 0, 1220, 50);

        jPanelListaCategorias.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaCategorias.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 225)));
        jPanelListaCategorias.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanelListaCategorias.setLayout(null);
        jPanelFondo.add(jPanelListaCategorias);
        jPanelListaCategorias.setBounds(20, 150, 820, 420);

        txtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBuscarKeyTyped(evt);
            }
        });
        jPanelFondo.add(txtBuscar);
        txtBuscar.setBounds(20, 80, 740, 42);

        cbInactivas.setText("Inactivas");
        jPanelFondo.add(cbInactivas);
        cbInactivas.setBounds(760, 100, 84, 20);

        jPanelListaCategorias1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelListaCategorias1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 225)));
        jPanelListaCategorias1.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanelListaCategorias1.setLayout(null);

        txtNombreCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreCategoriaKeyTyped(evt);
            }
        });
        jPanelListaCategorias1.add(txtNombreCategoria);
        txtNombreCategoria.setBounds(20, 70, 280, 42);

        btnEliminarCategoria.setBackground(new java.awt.Color(224, 223, 223));
        btnEliminarCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnEliminarCategoria.setForeground(new java.awt.Color(102, 102, 102));
        btnEliminarCategoria.setText("Eliminar");
        btnEliminarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCategoriaActionPerformed(evt);
            }
        });
        jPanelListaCategorias1.add(btnEliminarCategoria);
        btnEliminarCategoria.setBounds(170, 240, 130, 50);

        btnNuevaCategoria.setBackground(new java.awt.Color(17, 24, 39));
        btnNuevaCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnNuevaCategoria.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevaCategoria.setText("Nueva Categoria");
        btnNuevaCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevaCategoriaActionPerformed(evt);
            }
        });
        jPanelListaCategorias1.add(btnNuevaCategoria);
        btnNuevaCategoria.setBounds(20, 160, 280, 60);

        btnEditarCategoria.setBackground(new java.awt.Color(224, 223, 223));
        btnEditarCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnEditarCategoria.setForeground(new java.awt.Color(102, 102, 102));
        btnEditarCategoria.setText("Editar");
        btnEditarCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCategoriaActionPerformed(evt);
            }
        });
        jPanelListaCategorias1.add(btnEditarCategoria);
        btnEditarCategoria.setBounds(20, 240, 130, 50);

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(39, 24, 17));
        jLabel3.setText("Categorias");
        jLabel3.setAlignmentX(16.0F);
        jLabel3.setAlignmentY(0.0F);
        jPanelListaCategorias1.add(jLabel3);
        jLabel3.setBounds(20, 20, 270, 24);

        jPanelFondo.add(jPanelListaCategorias1);
        jPanelListaCategorias1.setBounds(860, 150, 320, 340);

        btnRegresar.setBackground(new java.awt.Color(224, 223, 223));
        btnRegresar.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 102, 102));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        jPanelFondo.add(btnRegresar);
        btnRegresar.setBounds(860, 520, 110, 50);

        getContentPane().add(jPanelFondo);
        jPanelFondo.setBounds(0, 0, 1230, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarKeyTyped
        // TODO add your handling code here:

    }//GEN-LAST:event_txtBuscarKeyTyped

    private void txtNombreCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreCategoriaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreCategoriaKeyTyped

    private void btnEliminarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarCategoriaActionPerformed

    private void btnNuevaCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevaCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevaCategoriaActionPerformed

    private void btnEditarCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarCategoriaActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarCategoria;
    private javax.swing.JButton btnEliminarCategoria;
    private javax.swing.JButton btnNuevaCategoria;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JCheckBox cbInactivas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelListaCategorias;
    private javax.swing.JPanel jPanelListaCategorias1;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtNombreCategoria;
    // End of variables declaration//GEN-END:variables
}
