/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import Entidades.Comanda;
import Entidades.Detallecomanda;
import Entidades.Usuario;
import Formularios.paneles.JPanelComandasGeneral;
import JPA.RolJpaController;
import JPA.UsuarioJpaController;
import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Polygon;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;


/**
 *
 * @author Sergio Arturo
 */
public class FrmComandas extends javax.swing.JFrame {

    
    
    UsuarioJpaController ctrlUsuario = new UsuarioJpaController();
    RolJpaController ctrlRol = new RolJpaController();
    
  
    FrmLogin login;
    
    public static Usuario usuario;
    
    
    Color colorSeleccion = Color.decode("#E0E0E0");
    Color colorNoSeleccion = Color.decode("#FFFFFF");
    Color colorHover = Color.decode("#F0F0F0");
    String seleccion = "productos";
    
    
    JPanelComandasGeneral panelComandaGeneral;
    
    public static Comanda comanda = null;
    public static Detallecomanda detalleComanda = null;
    
    
    
    /**
     * Creates new form FrmDetallesProductos
     */
    public FrmComandas(FrmLogin login, Usuario usuario) {
        initComponents();
        
        this.login = login;
        FrmComandas.usuario = usuario;
        
        cargarPanel();
        
        cargarDiseno();
        
    }
    
    
    private void cargarDiseno(){
        
        jblConfiguaracion.setVisible(false);
        
        for(int i = 0; i < usuario.getRolList().size(); i++){
            if(usuario.getRolList().get(i).getNombre().equalsIgnoreCase("Administrador")){
                jblConfiguaracion.setVisible(true);
            }
        }

        jblUsuario.setText(usuario.getNombreUsuario());
        
    }
    
    
    
    private void cargarPanel(){
        jPanelSeccion.removeAll();
        
        panelComandaGeneral = new JPanelComandasGeneral();
        
        panelComandaGeneral.setBounds(0,0,jPanelSeccion.getWidth(), jPanelSeccion.getHeight());
        
        jPanelSeccion.add(panelComandaGeneral);
        
        jPanelSeccion.revalidate();
        jPanelSeccion.repaint();
        
        
        
        
    }
   
    

    public Icon escalarImagen(URL path, int w, int h) {
        Image img = new ImageIcon(path).getImage();
        Image nueva = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(nueva);
    }

 
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelEncabezado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelSalir = new javax.swing.JPanel();
        jblSalir = new javax.swing.JLabel();
        jblConfiguaracion = new javax.swing.JLabel();
        jPanelSeccion = new javax.swing.JPanel();
        jPanelNavegacion = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jblUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Full Cup: Panel Administrador");
        setMinimumSize(new java.awt.Dimension(875, 566));
        setPreferredSize(new java.awt.Dimension(1230, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 707));
        getContentPane().setLayout(null);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(null);

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEncabezado.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(31, 41, 55));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanelEncabezado.add(jPanel3);
        jPanel3.setBounds(10, 10, 32, 32);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 24, 17));
        jLabel2.setText("Full Cup: Ventas");
        jLabel2.setAlignmentX(16.0F);
        jLabel2.setAlignmentY(0.0F);
        jPanelEncabezado.add(jLabel2);
        jLabel2.setBounds(50, 15, 400, 24);

        jPanelSalir.setBackground(new java.awt.Color(255, 51, 51));
        jPanelSalir.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanelSalir.setPreferredSize(new java.awt.Dimension(32, 32));
        jPanelSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelSalirMouseClicked(evt);
            }
        });
        jPanelSalir.setLayout(null);

        jblSalir.setBackground(new java.awt.Color(255, 255, 255));
        jblSalir.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblSalir.setText("Cerrar Sesion");
        jPanelSalir.add(jblSalir);
        jblSalir.setBounds(0, 0, 130, 30);

        jPanelEncabezado.add(jPanelSalir);
        jPanelSalir.setBounds(1060, 10, 130, 32);

        jblConfiguaracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/config.png"))); // NOI18N
        jblConfiguaracion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jblConfiguaracion.setPreferredSize(new java.awt.Dimension(36, 36));
        jblConfiguaracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblConfiguaracionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jblConfiguaracionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jblConfiguaracionMouseExited(evt);
            }
        });
        jPanelEncabezado.add(jblConfiguaracion);
        jblConfiguaracion.setBounds(1000, 8, 32, 32);

        jPanelFondo.add(jPanelEncabezado);
        jPanelEncabezado.setBounds(0, 0, 1216, 50);

        jPanelSeccion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSeccion.setLayout(null);
        jPanelFondo.add(jPanelSeccion);
        jPanelSeccion.setBounds(0, 110, 1216, 560);

        jPanelNavegacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNavegacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanelNavegacion.setMinimumSize(new java.awt.Dimension(1216, 60));
        jPanelNavegacion.setPreferredSize(new java.awt.Dimension(1216, 60));
        jPanelNavegacion.setLayout(null);
        jPanelNavegacion.add(jSeparator1);
        jSeparator1.setBounds(20, 50, 1190, 10);

        jblUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jblUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblUsuario.setText("Usuario");
        jPanelNavegacion.add(jblUsuario);
        jblUsuario.setBounds(968, 15, 220, 30);

        jPanelFondo.add(jPanelNavegacion);
        jPanelNavegacion.setBounds(0, 50, 1216, 60);

        getContentPane().add(jPanelFondo);
        jPanelFondo.setBounds(0, 0, 1230, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanelSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelSalirMouseClicked
        // TODO add your handling code here:
        usuario = null;
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jPanelSalirMouseClicked

    private void jblConfiguaracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfiguaracionMouseClicked
        // TODO add your handling code here:
        FrmPanelAdministrador administrador = new FrmPanelAdministrador(login);
        administrador.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jblConfiguaracionMouseClicked

    private void jblConfiguaracionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfiguaracionMouseEntered
        // TODO add your handling code here:

        jblConfiguaracion.setIcon(escalarImagen(getClass().getResource("/iconos/configSelect.png"), 32, 32));
    


    }//GEN-LAST:event_jblConfiguaracionMouseEntered

    private void jblConfiguaracionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblConfiguaracionMouseExited
        // TODO add your handling code here:
        jblConfiguaracion.setIcon(escalarImagen(getClass().getResource("/iconos/config.png"), 32, 32));
    }//GEN-LAST:event_jblConfiguaracionMouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelNavegacion;
    private javax.swing.JPanel jPanelSalir;
    public static javax.swing.JPanel jPanelSeccion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jblConfiguaracion;
    private javax.swing.JLabel jblSalir;
    private javax.swing.JLabel jblUsuario;
    // End of variables declaration//GEN-END:variables
}
