/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


import Entidades.Comanda;
import Entidades.Detallecomanda;
import Formularios.paneles.JPanelComandasGeneral;
import java.awt.Color;


/**
 *
 * @author Sergio Arturo
 */
public class FrmComandas extends javax.swing.JFrame {

  
    FrmLogin login;
    
    
    Color colorSeleccion = Color.decode("#E0E0E0");
    Color colorNoSeleccion = Color.decode("#FFFFFF");
    Color colorHover = Color.decode("#F0F0F0");
    String seleccion = "productos";
    
    
    JPanelComandasGeneral panelComandaGeneral;
    
    public static Comanda comanda = null;
    public static Detallecomanda detalleComanda = null;
    
    
    
    /**
     * Creates new form FrmDetallesProductos
     */
    public FrmComandas(FrmLogin login) {
        initComponents();
        
        this.login = login;
        
        cargarPanel();
        
    }
    
    
    
    
    private void cargarPanel(){
        jPanelSeccion.removeAll();
        
        panelComandaGeneral = new JPanelComandasGeneral();
        
        panelComandaGeneral.setBounds(0,0,1210, 560);
        
        jPanelSeccion.add(panelComandaGeneral);
        
        jPanelSeccion.revalidate();
        jPanelSeccion.repaint();
        
        
    }
   
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmComandas().setVisible(true);
//            }
//        });
//    }
    
 
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelEncabezado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jblSalir = new javax.swing.JLabel();
        jPanelSeccion = new javax.swing.JPanel();
        jPanelNavegacion = new javax.swing.JPanel();
        jblNavegacionSeparador1 = new javax.swing.JLabel();
        jblNavegacionComandas = new javax.swing.JLabel();
        jblNavegacionComandas1 = new javax.swing.JLabel();
        jblNavegacionComandas2 = new javax.swing.JLabel();
        jblNavegacionSeparador2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Full Cup: Panel Administrador");
        setMinimumSize(new java.awt.Dimension(875, 566));
        setPreferredSize(new java.awt.Dimension(1230, 707));
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 707));
        getContentPane().setLayout(null);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(null);

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEncabezado.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(31, 41, 55));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanelEncabezado.add(jPanel3);
        jPanel3.setBounds(10, 10, 32, 32);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 24, 17));
        jLabel2.setText("Full Cup: Ventas");
        jLabel2.setAlignmentX(16.0F);
        jLabel2.setAlignmentY(0.0F);
        jPanelEncabezado.add(jLabel2);
        jLabel2.setBounds(50, 15, 400, 24);

        jblSalir.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jblSalir.setForeground(new java.awt.Color(39, 24, 17));
        jblSalir.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblSalir.setText("Salir");
        jblSalir.setAlignmentX(16.0F);
        jblSalir.setAlignmentY(0.0F);
        jblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblSalirMouseClicked(evt);
            }
        });
        jPanelEncabezado.add(jblSalir);
        jblSalir.setBounds(1140, 15, 50, 24);

        jPanelFondo.add(jPanelEncabezado);
        jPanelEncabezado.setBounds(0, 0, 1216, 50);

        jPanelSeccion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelSeccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelSeccion.setLayout(null);
        jPanelFondo.add(jPanelSeccion);
        jPanelSeccion.setBounds(0, 110, 1216, 560);

        jPanelNavegacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanelNavegacion.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 1, new java.awt.Color(0, 0, 0)));
        jPanelNavegacion.setMinimumSize(new java.awt.Dimension(1216, 60));
        jPanelNavegacion.setPreferredSize(new java.awt.Dimension(1216, 60));
        jPanelNavegacion.setLayout(null);

        jblNavegacionSeparador1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNavegacionSeparador1.setForeground(new java.awt.Color(102, 102, 102));
        jblNavegacionSeparador1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNavegacionSeparador1.setText(">");
        jPanelNavegacion.add(jblNavegacionSeparador1);
        jblNavegacionSeparador1.setBounds(90, 16, 20, 27);

        jblNavegacionComandas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblNavegacionComandas.setForeground(new java.awt.Color(102, 102, 102));
        jblNavegacionComandas.setText("Detalle Comanda\n");
        jblNavegacionComandas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jblNavegacionComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblNavegacionComandasMouseClicked(evt);
            }
        });
        jPanelNavegacion.add(jblNavegacionComandas);
        jblNavegacionComandas.setBounds(125, 20, 110, 25);

        jblNavegacionComandas1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblNavegacionComandas1.setForeground(new java.awt.Color(102, 102, 102));
        jblNavegacionComandas1.setText("Comandas");
        jblNavegacionComandas1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jblNavegacionComandas1MouseClicked(evt);
            }
        });
        jPanelNavegacion.add(jblNavegacionComandas1);
        jblNavegacionComandas1.setBounds(20, 20, 60, 25);

        jblNavegacionComandas2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jblNavegacionComandas2.setForeground(new java.awt.Color(102, 102, 102));
        jblNavegacionComandas2.setText("<html> <u>Detalle del Producto</u> </html> ");
        jPanelNavegacion.add(jblNavegacionComandas2);
        jblNavegacionComandas2.setBounds(275, 20, 120, 25);

        jblNavegacionSeparador2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jblNavegacionSeparador2.setForeground(new java.awt.Color(102, 102, 102));
        jblNavegacionSeparador2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jblNavegacionSeparador2.setText(">");
        jPanelNavegacion.add(jblNavegacionSeparador2);
        jblNavegacionSeparador2.setBounds(235, 16, 20, 27);
        jPanelNavegacion.add(jSeparator1);
        jSeparator1.setBounds(20, 50, 1190, 10);

        jPanelFondo.add(jPanelNavegacion);
        jPanelNavegacion.setBounds(0, 50, 1216, 60);

        getContentPane().add(jPanelFondo);
        jPanelFondo.setBounds(0, 0, 1230, 670);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jblNavegacionComandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblNavegacionComandasMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_jblNavegacionComandasMouseClicked

    private void jblNavegacionComandas1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblNavegacionComandas1MouseClicked
        // TODO add your handling code here:
        FrmComandas.jPanelSeccion.removeAll();
        
        JPanelComandasGeneral panelGeneral = new JPanelComandasGeneral();
        
        panelGeneral.setBounds(0, 0, FrmComandas.jPanelSeccion.getWidth(), FrmComandas.jPanelSeccion.getHeight());
        FrmComandas.jPanelSeccion.add(panelGeneral);

        FrmComandas.jPanelSeccion.revalidate();
        FrmComandas.jPanelSeccion.repaint();
        
        
    }//GEN-LAST:event_jblNavegacionComandas1MouseClicked

    private void jblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jblSalirMouseClicked
        // TODO add your handling code here:
        login.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jblSalirMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelNavegacion;
    public static javax.swing.JPanel jPanelSeccion;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jblNavegacionComandas;
    private javax.swing.JLabel jblNavegacionComandas1;
    private javax.swing.JLabel jblNavegacionComandas2;
    private javax.swing.JLabel jblNavegacionSeparador1;
    private javax.swing.JLabel jblNavegacionSeparador2;
    private javax.swing.JLabel jblSalir;
    // End of variables declaration//GEN-END:variables
}
