/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Entidades.Cajaefectivo;
import JPA.CajaefectivoJpaController;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Sergio Arturo
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAdmin = new javax.swing.JButton();
        btnAtendiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Full Cup: Login");
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 620));

        jPanel1.setMinimumSize(new java.awt.Dimension(1230, 620));
        jPanel1.setLayout(null);

        btnAdmin.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAdmin.setText("Administrador");
        btnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnAdmin);
        btnAdmin.setBounds(468, 120, 291, 97);

        btnAtendiente.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnAtendiente.setText("Atendiente");
        btnAtendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtendienteActionPerformed(evt);
            }
        });
        jPanel1.add(btnAtendiente);
        btnAtendiente.setBounds(470, 320, 291, 97);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtendienteActionPerformed
        CajaefectivoJpaController cajaController = new CajaefectivoJpaController();
        Cajaefectivo cajaAbierta = cajaController.obtenerCajaAbierta();

        if (cajaAbierta == null) {
            // -----------------------
            // NO EXISTE CAJA ABIERTA
            // -----------------------
            String montoStr = javax.swing.JOptionPane.showInputDialog(
                    this,
                    "Ingresa el monto inicial de la caja:",
                    "Monto Inicial",
                    javax.swing.JOptionPane.PLAIN_MESSAGE
            );

            if (montoStr == null) {
                javax.swing.JOptionPane.showMessageDialog(this, "Debes ingresar un monto para continuar.");
                return;
            }

            float montoInicial;
            try {
                montoInicial = Float.parseFloat(montoStr);
            } catch (NumberFormatException e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Ingresa un valor numérico válido.");
                return;
            }

            // Crear nueva caja
            Cajaefectivo nuevaCaja = new Cajaefectivo();
            nuevaCaja.setIdCorte((int) (System.currentTimeMillis() % Integer.MAX_VALUE)); // ID único
            nuevaCaja.setMontoInicial(montoInicial);
            nuevaCaja.setEstado((short) 0); // 0 = ABIERTA
            nuevaCaja.setTipoCorte('X'); // Corte del día (puedes cambiar)
            nuevaCaja.setIdUsuario(null); // Si quieres asignarle un usuario, aquí se coloca

            try {
                cajaController.create(nuevaCaja);
            } catch (Exception ex) {
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error al crear caja.");
                return;
            }

            javax.swing.JOptionPane.showMessageDialog(this, "Caja iniciada correctamente.");
        } else {
            // YA EXISTE CAJA ABIERTA → NO PEDIR MONTO
            System.out.println("La caja ya estaba abierta, no se pide monto.");
        }

        // Entrar al sistema
        FrmComandas comandas = new FrmComandas();
        comandas.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_btnAtendienteActionPerformed

    private void btnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminActionPerformed
        // TODO add your handling code here:

        FrmPanelAdministrador admin = new FrmPanelAdministrador(this);
        admin.setVisible(true);
        this.setVisible(false);


    }//GEN-LAST:event_btnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            javax.swing.UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(FrmLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdmin;
    private javax.swing.JButton btnAtendiente;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
