/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;

import Entidades.Cajaefectivo;
import Entidades.Venta;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class FrmPanelCorteZ extends javax.swing.JFrame {

    JPA.VentaJpaController ctrlVenta = new JPA.VentaJpaController();
    JPA.CajaefectivoJpaController ctrlCaja = new JPA.CajaefectivoJpaController();

    /**
     * Creates new form FrmPanelCorteZ
     */
    public FrmPanelCorteZ() {
        initComponents();
        cargarDatosCorteZ();
    }

    private void cargarDatosCorteZ() {

        try {

            List<Venta> ventas = ctrlVenta.obtenerVentasDeHoy();

            double totalEfectivo = 0;
            double totalTarjeta = 0;

            for (Venta v : ventas) {

                if (v.getMetodoPago().equalsIgnoreCase("EFECTIVO")) {
                    totalEfectivo += v.getTotal();
                }

                if (v.getMetodoPago().equalsIgnoreCase("TARJETA")) {
                    totalTarjeta += v.getTotal();
                }
            }

            double totalVentas = totalEfectivo + totalTarjeta;

            Cajaefectivo caja = ctrlCaja.obtenerCajaAbierta();

            lblMontoInicial.setText("$ " + caja.getMontoInicial());
            lblTotalEfectivo.setText("$ " + totalEfectivo);
            lblTotalTarjeta.setText("$ " + totalTarjeta);
            lblTotalVentas.setText("$ " + totalVentas);
            lblMontoFinal.setText("$ " + (caja.getMontoInicial() + totalEfectivo));

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public void cargarDatosCorteZ(double montoInicial, double ventasTotales,
            double efectivo, double tarjeta,
            double transferencia, double mixto) {

        lblMontoInicial.setText("$" + montoInicial);
        lblTotalVentas.setText("$" + ventasTotales);

        double dineroEsperado = montoInicial + efectivo;
        lblMontoFinal.setText("$" + dineroEsperado);

        lblTotalEfectivo.setText("$" + efectivo);
        lblTotalTarjeta.setText("$" + tarjeta);
        txtTransferenciaMonto.setText("$" + transferencia);
        txtMixtoMonto.setText("$" + mixto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMontoInicial = new javax.swing.JLabel();
        lblMontoInicial = new javax.swing.JLabel();
        txtVentasTotales = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        txtDineroEsperado = new javax.swing.JLabel();
        lblMontoFinal = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JLabel();
        lblTotalEfectivo = new javax.swing.JLabel();
        lblTotalTarjeta = new javax.swing.JLabel();
        txtTarjeta = new javax.swing.JLabel();
        txtTransferencia = new javax.swing.JLabel();
        txtTransferenciaMonto = new javax.swing.JLabel();
        txtMixto = new javax.swing.JLabel();
        txtMixtoMonto = new javax.swing.JLabel();
        txtMontoContadoEnCaja = new javax.swing.JTextField();
        btnCierreDeCaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtMontoInicial.setText("Monto Inicial");

        lblMontoInicial.setText("$0");

        txtVentasTotales.setText("Ventas totales");

        lblTotalVentas.setText("$0");

        txtDineroEsperado.setText("Efectivo esperado");

        lblMontoFinal.setText("$0");

        txtEfectivo.setText("Efectivo");

        lblTotalEfectivo.setText("$0");

        lblTotalTarjeta.setText("$0");

        txtTarjeta.setText("Tarjeta");

        txtTransferencia.setText("Transferencia");

        txtTransferenciaMonto.setText("$0");

        txtMixto.setText("Mixto");

        txtMixtoMonto.setText("$0");

        txtMontoContadoEnCaja.setText("$");
        txtMontoContadoEnCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMontoContadoEnCajaActionPerformed(evt);
            }
        });

        btnCierreDeCaja.setText("Cierre de caja");
        btnCierreDeCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCierreDeCajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(txtMontoInicial)
                .addGap(157, 157, 157)
                .addComponent(txtVentasTotales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(txtDineroEsperado)
                .addGap(112, 112, 112))
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtEfectivo)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtMixto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMixtoMonto))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTransferencia)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtTransferenciaMonto))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblMontoInicial)
                                .addGap(211, 211, 211)
                                .addComponent(lblTotalVentas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMontoFinal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblTotalEfectivo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtTarjeta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblTotalTarjeta)))
                        .addGap(154, 154, 154))))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(txtMontoContadoEnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156)
                .addComponent(btnCierreDeCaja)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoInicial)
                    .addComponent(txtVentasTotales)
                    .addComponent(txtDineroEsperado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMontoInicial)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTotalVentas)
                        .addComponent(lblMontoFinal)))
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEfectivo)
                    .addComponent(lblTotalEfectivo))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTarjeta)
                    .addComponent(lblTotalTarjeta))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTransferencia)
                    .addComponent(txtTransferenciaMonto))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMixto)
                    .addComponent(txtMixtoMonto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMontoContadoEnCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCierreDeCaja))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtMontoContadoEnCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMontoContadoEnCajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMontoContadoEnCajaActionPerformed

    private void btnCierreDeCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCierreDeCajaActionPerformed
        try {

            Cajaefectivo caja = ctrlCaja.obtenerCajaAbierta();
            if (caja == null) {
                JOptionPane.showMessageDialog(null, "No hay caja abierta.");
                return;
            }

            // Valores calculados previamente
            double montoFinal = caja.getMontoInicial() + Double.parseDouble(lblTotalEfectivo.getText().replace("$ ", ""));

            caja.setMontoFinal((float) montoFinal);
            caja.setEstado((short) 1);
            caja.setTipoCorte('Z');

            ctrlCaja.edit(caja);

            JOptionPane.showMessageDialog(null,
                    "Corte Z generado correctamente.\n"
                    + "Monto Final: $" + montoFinal,
                    "Corte Z", JOptionPane.INFORMATION_MESSAGE);

            this.dispose();

        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }//GEN-LAST:event_btnCierreDeCajaActionPerformed

    private void cerrarCaja() {
        double contado = Double.parseDouble(txtMontoContadoEnCaja.getText().replace("$", ""));

        double esperado = Double.parseDouble(lblMontoFinal.getText().replace("$", ""));

        double diferencia = contado - esperado;

        JOptionPane.showMessageDialog(this,
                "Cierre realizado\n"
                + "Esperado: $" + esperado + "\n"
                + "Contado: $" + contado + "\n"
                + "Diferencia: " + diferencia);

        // Aquí llamas a tu DAO para registrar y reiniciar montos
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPanelCorteZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPanelCorteZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPanelCorteZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPanelCorteZ.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPanelCorteZ().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCierreDeCaja;
    private javax.swing.JLabel lblMontoFinal;
    private javax.swing.JLabel lblMontoInicial;
    private javax.swing.JLabel lblTotalEfectivo;
    private javax.swing.JLabel lblTotalTarjeta;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JLabel txtDineroEsperado;
    private javax.swing.JLabel txtEfectivo;
    private javax.swing.JLabel txtMixto;
    private javax.swing.JLabel txtMixtoMonto;
    private javax.swing.JTextField txtMontoContadoEnCaja;
    private javax.swing.JLabel txtMontoInicial;
    private javax.swing.JLabel txtTarjeta;
    private javax.swing.JLabel txtTransferencia;
    private javax.swing.JLabel txtTransferenciaMonto;
    private javax.swing.JLabel txtVentasTotales;
    // End of variables declaration//GEN-END:variables
}
