/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Formularios;


/**
 *
 * @author Sergio Arturo
 */
public class FrmPanelAdministrador extends javax.swing.JFrame {

  
    FrmLogin login;
    
    
    /**
     * Creates new form FrmDetallesProductos
     */
    public FrmPanelAdministrador(FrmLogin login) {
        initComponents();
        
        this.login = login;
        
        
    }
    
   
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanelEncabezado = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAdministrarCategorias = new javax.swing.JButton();
        btnAdministrarCortes = new javax.swing.JButton();
        btnAdministrarProductos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Comanda: Detalles del Producto");
        setMinimumSize(new java.awt.Dimension(1230, 620));
        setResizable(false);
        setSize(new java.awt.Dimension(1230, 620));
        getContentPane().setLayout(null);

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(null);

        jPanelEncabezado.setBackground(new java.awt.Color(255, 255, 255));
        jPanelEncabezado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelEncabezado.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(31, 41, 55));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(32, 32));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 26, Short.MAX_VALUE)
        );

        jPanelEncabezado.add(jPanel3);
        jPanel3.setBounds(10, 10, 32, 32);

        jLabel2.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(39, 24, 17));
        jLabel2.setText("Café Express POS: Panel Administrador");
        jLabel2.setAlignmentX(16.0F);
        jLabel2.setAlignmentY(0.0F);
        jPanelEncabezado.add(jLabel2);
        jLabel2.setBounds(50, 15, 830, 24);

        jPanelFondo.add(jPanelEncabezado);
        jPanelEncabezado.setBounds(0, 0, 1230, 50);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 231, 225)));
        jPanel4.setPreferredSize(new java.awt.Dimension(500, 200));
        jPanel4.setLayout(null);

        btnAdministrarCategorias.setBackground(new java.awt.Color(17, 24, 39));
        btnAdministrarCategorias.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnAdministrarCategorias.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarCategorias.setText("Administrar Categorias");
        btnAdministrarCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarCategoriasActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdministrarCategorias);
        btnAdministrarCategorias.setBounds(70, 150, 210, 60);

        btnAdministrarCortes.setBackground(new java.awt.Color(17, 24, 39));
        btnAdministrarCortes.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnAdministrarCortes.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarCortes.setText("Administrar Cortes");
        btnAdministrarCortes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarCortesActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdministrarCortes);
        btnAdministrarCortes.setBounds(70, 260, 210, 60);

        btnAdministrarProductos.setBackground(new java.awt.Color(17, 24, 39));
        btnAdministrarProductos.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnAdministrarProductos.setForeground(new java.awt.Color(255, 255, 255));
        btnAdministrarProductos.setText("Administrar Productos");
        btnAdministrarProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrarProductosActionPerformed(evt);
            }
        });
        jPanel4.add(btnAdministrarProductos);
        btnAdministrarProductos.setBounds(70, 38, 210, 60);

        jPanelFondo.add(jPanel4);
        jPanel4.setBounds(20, 70, 370, 470);

        getContentPane().add(jPanelFondo);
        jPanelFondo.setBounds(0, 0, 1230, 720);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrarCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarCategoriasActionPerformed
        // TODO add your handling code here:

        FrmAdministrarCategorias categorias = new FrmAdministrarCategorias(this);
        categorias.setVisible(true);
        this.setVisible(false);
        
        
    }//GEN-LAST:event_btnAdministrarCategoriasActionPerformed

    private void btnAdministrarCortesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarCortesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarCortesActionPerformed

    private void btnAdministrarProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrarProductosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdministrarProductosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrarCategorias;
    private javax.swing.JButton btnAdministrarCortes;
    private javax.swing.JButton btnAdministrarProductos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelEncabezado;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
