/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles;


import Entidades.Cajaefectivo;
import Entidades.Venta;
import Formularios.FrmComandas;
import JPA.HistorialcorteJpaController;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import utilerias.ConstantesGUI;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelCorteX extends javax.swing.JPanel {

    
    JPA.VentaJpaController ctrlVenta = new JPA.VentaJpaController();
    double totalEfectivo = 0;
    double totalTarjeta = 0;
    double totalTransferencia = 0;
    double totalMixto = 0;
    
    
    /**
     * Creates new form JPanelComandas
     */
    public JPanelCorteX() {
        initComponents();
        
        
        cargarDiseno();
        
        calcularCorteX();
        
    }
    
    
    private void cargarDiseno(){
        

    }
    
    
    
    private void calcularCorteX() {

        try {

            // 1. Obtener ventas del día (o fecha seleccionada)
            List<Venta> ventas = ctrlVenta.obtenerVentasDeHoy();

            for (Venta v : ventas) {

                switch (v.getMetodoPago().toUpperCase()) {

                    case "EFECTIVO":
                        totalEfectivo += v.getTotal();
                        break;

                    case "TARJETA":
                        totalTarjeta += v.getTotal();
                        break;

                    case "TRANSFERENCIA":
                        totalTransferencia += v.getTotal();
                        break;

                    case "MIXTO":
                        totalMixto += v.getTotal();
                        break;
                }
            }

            double totalVentas = totalEfectivo + totalTarjeta + totalTransferencia + totalMixto;

            // 2. Mostrar en pantalla
            lblTotalVentas.setText("$ " + totalVentas);
            lblTotalEfectivo.setText("$ " + totalEfectivo);
            lblTotalTarjeta.setText("$ " + totalTarjeta);
            txtTransferenciaMonto.setText("$ " + totalTransferencia);
            txtMixtoMonto.setText("$ " + totalMixto);

            // 3. Calcular monto estimado en caja
            double montoInicial = obtenerMontoInicialDelDia();

            lblMontoEsperadoCaja.setText("$ " + (montoInicial + totalEfectivo));

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    
    
    
    
    private double obtenerMontoInicialDelDia() {
        try {
            JPA.CajaefectivoJpaController ctrlCaja = new JPA.CajaefectivoJpaController();
            Cajaefectivo caja = ctrlCaja.obtenerCajaAbierta();

            if (caja != null) {
                return caja.getMontoInicial();
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
        return 0;
    }
    
    
    

        public void cargarDatosCorteX(double montoInicial, double ventasTotales,
            double efectivo, double tarjeta,
            double transferencia, double mixto) {

        txtMontoInicialMonto.setText("$" + montoInicial);
        lblTotalVentas.setText("$" + ventasTotales);

        double dineroEsperado = montoInicial + efectivo;
        lblMontoEsperadoCaja.setText("$" + dineroEsperado);

        lblTotalEfectivo.setText("$" + efectivo);
        lblTotalTarjeta.setText("$" + tarjeta);
        txtTransferenciaMonto.setText("$" + transferencia);
        txtMixtoMonto.setText("$" + mixto);

    }
    
    
        
    private void volverSeccionAnterior(){
        
        FrmComandas.comanda = null;
        FrmComandas.detalleComanda = null;
        
        FrmComandas.jPanelSeccion.removeAll();
        
        JPanelComandasGeneral panelGeneral = new JPanelComandasGeneral();
        
        panelGeneral.setBounds(0, 0, FrmComandas.jPanelSeccion.getWidth(), FrmComandas.jPanelSeccion.getHeight());
        FrmComandas.jPanelSeccion.add(panelGeneral);

        FrmComandas.jPanelSeccion.revalidate();
        FrmComandas.jPanelSeccion.repaint();
        
    
    }    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblTitulo = new javax.swing.JLabel();
        jPanelDesglose = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtMixtoMonto = new javax.swing.JLabel();
        txtEfectivo3 = new javax.swing.JLabel();
        jblSubtitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblTotalEfectivo = new javax.swing.JLabel();
        txtEfectivo = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblTotalTarjeta = new javax.swing.JLabel();
        txtEfectivo1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTransferenciaMonto = new javax.swing.JLabel();
        txtEfectivo2 = new javax.swing.JLabel();
        jPanelEfectivoEsperado = new javax.swing.JPanel();
        txtDineroEsperado = new javax.swing.JLabel();
        lblMontoEsperadoCaja = new javax.swing.JLabel();
        jPanelMontoInicial = new javax.swing.JPanel();
        txtMontoInicial = new javax.swing.JLabel();
        txtMontoInicialMonto = new javax.swing.JLabel();
        jPanelVentaTotales = new javax.swing.JPanel();
        txtVentasTotales = new javax.swing.JLabel();
        lblTotalVentas = new javax.swing.JLabel();
        txtMontoContadoEnCaja = new javax.swing.JTextField();
        jblSubtitulo1 = new javax.swing.JLabel();
        btnCorteCaja = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(1210, 560));
        setPreferredSize(new java.awt.Dimension(1210, 560));
        setLayout(null);

        jblTitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 36)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(39, 24, 17));
        jblTitulo.setText("Corte X: Consulta intermedia");
        jblTitulo.setAlignmentX(16.0F);
        jblTitulo.setAlignmentY(0.0F);
        add(jblTitulo);
        jblTitulo.setBounds(20, 30, 500, 40);

        jPanelDesglose.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDesglose.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        jPanelDesglose.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(241, 241, 241));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(null);

        txtMixtoMonto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtMixtoMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtMixtoMonto.setText("$0");
        jPanel1.add(txtMixtoMonto);
        txtMixtoMonto.setBounds(402, 10, 150, 40);

        txtEfectivo3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEfectivo3.setForeground(new java.awt.Color(102, 102, 102));
        txtEfectivo3.setText("Mixto");
        jPanel1.add(txtEfectivo3);
        txtEfectivo3.setBounds(50, 10, 100, 40);

        jPanelDesglose.add(jPanel1);
        jPanel1.setBounds(10, 260, 580, 60);

        jblSubtitulo.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jblSubtitulo.setText("Desglose por metodo de pago");
        jblSubtitulo.setAlignmentX(16.0F);
        jblSubtitulo.setAlignmentY(0.0F);
        jPanelDesglose.add(jblSubtitulo);
        jblSubtitulo.setBounds(10, 10, 430, 30);

        jPanel2.setBackground(new java.awt.Color(241, 241, 241));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel2.setLayout(null);

        lblTotalEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalEfectivo.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalEfectivo.setText("$0");
        jPanel2.add(lblTotalEfectivo);
        lblTotalEfectivo.setBounds(390, 10, 160, 40);

        txtEfectivo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEfectivo.setForeground(new java.awt.Color(102, 102, 102));
        txtEfectivo.setText("Efectivo");
        jPanel2.add(txtEfectivo);
        txtEfectivo.setBounds(50, 10, 100, 40);

        jPanelDesglose.add(jPanel2);
        jPanel2.setBounds(10, 50, 580, 60);

        jPanel3.setBackground(new java.awt.Color(241, 241, 241));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel3.setLayout(null);

        lblTotalTarjeta.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTotalTarjeta.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblTotalTarjeta.setText("$0");
        jPanel3.add(lblTotalTarjeta);
        lblTotalTarjeta.setBounds(380, 10, 170, 40);

        txtEfectivo1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEfectivo1.setForeground(new java.awt.Color(102, 102, 102));
        txtEfectivo1.setText("Tarjeta");
        jPanel3.add(txtEfectivo1);
        txtEfectivo1.setBounds(50, 10, 100, 40);

        jPanelDesglose.add(jPanel3);
        jPanel3.setBounds(10, 120, 580, 60);

        jPanel4.setBackground(new java.awt.Color(241, 241, 241));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel4.setLayout(null);

        txtTransferenciaMonto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtTransferenciaMonto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        txtTransferenciaMonto.setText("$0");
        jPanel4.add(txtTransferenciaMonto);
        txtTransferenciaMonto.setBounds(392, 10, 160, 40);

        txtEfectivo2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtEfectivo2.setForeground(new java.awt.Color(102, 102, 102));
        txtEfectivo2.setText("Transferencia");
        jPanel4.add(txtEfectivo2);
        txtEfectivo2.setBounds(50, 10, 160, 40);

        jPanelDesglose.add(jPanel4);
        jPanel4.setBounds(10, 190, 580, 60);

        add(jPanelDesglose);
        jPanelDesglose.setBounds(20, 140, 600, 340);

        jPanelEfectivoEsperado.setBackground(new java.awt.Color(236, 254, 255));
        jPanelEfectivoEsperado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelEfectivoEsperado.setLayout(null);

        txtDineroEsperado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtDineroEsperado.setText("Efectivo esperado");
        jPanelEfectivoEsperado.add(txtDineroEsperado);
        txtDineroEsperado.setBounds(20, 15, 180, 25);

        lblMontoEsperadoCaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblMontoEsperadoCaja.setText("$0");
        jPanelEfectivoEsperado.add(lblMontoEsperadoCaja);
        lblMontoEsperadoCaja.setBounds(20, 46, 150, 30);

        add(jPanelEfectivoEsperado);
        jPanelEfectivoEsperado.setBounds(670, 380, 350, 100);

        jPanelMontoInicial.setBackground(new java.awt.Color(255, 255, 255));
        jPanelMontoInicial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelMontoInicial.setLayout(null);

        txtMontoInicial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtMontoInicial.setText("Monto Inicial");
        jPanelMontoInicial.add(txtMontoInicial);
        txtMontoInicial.setBounds(20, 15, 140, 25);

        txtMontoInicialMonto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMontoInicialMonto.setText("$0");
        jPanelMontoInicial.add(txtMontoInicialMonto);
        txtMontoInicialMonto.setBounds(20, 50, 120, 30);

        add(jPanelMontoInicial);
        jPanelMontoInicial.setBounds(670, 140, 350, 100);

        jPanelVentaTotales.setBackground(new java.awt.Color(255, 255, 255));
        jPanelVentaTotales.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelVentaTotales.setLayout(null);

        txtVentasTotales.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtVentasTotales.setText("Ventas totales");
        jPanelVentaTotales.add(txtVentasTotales);
        txtVentasTotales.setBounds(20, 10, 140, 25);

        lblTotalVentas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalVentas.setText("$0");
        jPanelVentaTotales.add(lblTotalVentas);
        lblTotalVentas.setBounds(20, 46, 120, 30);

        add(jPanelVentaTotales);
        jPanelVentaTotales.setBounds(670, 260, 350, 100);
        add(txtMontoContadoEnCaja);
        txtMontoContadoEnCaja.setBounds(230, 500, 220, 40);

        jblSubtitulo1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jblSubtitulo1.setForeground(new java.awt.Color(102, 102, 102));
        jblSubtitulo1.setText("Consulta de efectivo sin cerrar el turno");
        jblSubtitulo1.setAlignmentX(16.0F);
        jblSubtitulo1.setAlignmentY(0.0F);
        add(jblSubtitulo1);
        jblSubtitulo1.setBounds(20, 80, 680, 40);

        btnCorteCaja.setBackground(new java.awt.Color(17, 24, 39));
        btnCorteCaja.setFont(new java.awt.Font("Helvetica Neue", 1, 12)); // NOI18N
        btnCorteCaja.setForeground(new java.awt.Color(255, 255, 255));
        btnCorteCaja.setText("Corte de caja");
        btnCorteCaja.setBorder(null);
        btnCorteCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorteCajaActionPerformed(evt);
            }
        });
        add(btnCorteCaja);
        btnCorteCaja.setBounds(490, 500, 130, 38);

        btnCancelar.setBackground(new java.awt.Color(242, 243, 245));
        btnCancelar.setForeground(new java.awt.Color(55, 65, 81));
        btnCancelar.setText("Volver");
        btnCancelar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnCancelar.setMaximumSize(new java.awt.Dimension(180, 40));
        btnCancelar.setPreferredSize(new java.awt.Dimension(180, 40));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        add(btnCancelar);
        btnCancelar.setBounds(930, 90, 90, 40);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCorteCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorteCajaActionPerformed
        // TODO add your handling code here:
                try {
            String texto = txtMontoContadoEnCaja.getText().replace("$", "").trim();
            double montoContado = Double.parseDouble(texto);
            JPA.CajaefectivoJpaController ctrlCaja = new JPA.CajaefectivoJpaController();
            Cajaefectivo cajaActual = ctrlCaja.obtenerCajaAbierta();

            if (cajaActual == null) {
                JOptionPane.showMessageDialog(this, "No hay caja abierta.");
                return;
            }

            double esperado = cajaActual.getMontoInicial();
            double diferencia = montoContado - esperado;

            cajaActual.setMontoFinal((float) montoContado);
            cajaActual.setDiferencia((float) diferencia);
            cajaActual.setFechaHoraCorte(new Date());
            cajaActual.setTipoCorte('X');
            cajaActual.setEstado((short) 0);

            ctrlCaja.edit(cajaActual);

            // ---- GUARDAR HISTORIAL ----
            HistorialcorteJpaController ctrlHist = new HistorialcorteJpaController();
            ctrlHist.registrarHistorial(cajaActual, 'X');

            JOptionPane.showMessageDialog(this,
                    "Corte X realizado.\nDiferencia: $" + diferencia);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al hacer corte X: " + ex.getMessage());
        }
    }//GEN-LAST:event_btnCorteCajaActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
        volverSeccionAnterior();

    }//GEN-LAST:event_btnCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCorteCaja;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanelDesglose;
    private javax.swing.JPanel jPanelEfectivoEsperado;
    private javax.swing.JPanel jPanelMontoInicial;
    private javax.swing.JPanel jPanelVentaTotales;
    private javax.swing.JLabel jblSubtitulo;
    private javax.swing.JLabel jblSubtitulo1;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel lblMontoEsperadoCaja;
    private javax.swing.JLabel lblTotalEfectivo;
    private javax.swing.JLabel lblTotalTarjeta;
    private javax.swing.JLabel lblTotalVentas;
    private javax.swing.JLabel txtDineroEsperado;
    private javax.swing.JLabel txtEfectivo;
    private javax.swing.JLabel txtEfectivo1;
    private javax.swing.JLabel txtEfectivo2;
    private javax.swing.JLabel txtEfectivo3;
    private javax.swing.JLabel txtMixtoMonto;
    private javax.swing.JTextField txtMontoContadoEnCaja;
    private javax.swing.JLabel txtMontoInicial;
    private javax.swing.JLabel txtMontoInicialMonto;
    private javax.swing.JLabel txtTransferenciaMonto;
    private javax.swing.JLabel txtVentasTotales;
    // End of variables declaration//GEN-END:variables
}
