/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles;

import Entidades.Categoria;
import Entidades.Producto;
import Facades.IFachadaCategoriaControlador;
import Facades.IFachadaProductoControlador;
import Formularios.paneles.elementos.JPanelProducto;
import Implementaciones.GestionarCategoriaControlador;
import Implementaciones.GestionarProductoControlador;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.SwingUtilities;
import utilerias.ConstantesGUI;
import utilerias.HintToTextField;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelAdminProductosCRUD extends javax.swing.JPanel {
    
    
    private final IFachadaCategoriaControlador fCategoria = new GestionarCategoriaControlador();
    private final IFachadaProductoControlador fProducto = new GestionarProductoControlador();
    
    
    ConstantesGUI accion;
    
    
    Dimension dimension = null;
    
    List <Producto> listaProductos;
    List <Categoria> listaCategorias;
    
    

    /**
     * Creates new form JPanelAdminCategorias
     */
    public JPanelAdminProductosCRUD(ConstantesGUI accion) {
        initComponents();
        
        this.accion = accion;
        
        
        cargarDiseno();
        
        
        
        
        
    }
    
    
          

    
    private void cargarDiseno(){
           
        cargarCategorias();
       
        accionesConstantesGUI();
        
        
    }
    
    
    private void cargarCategorias() {

        List<String> listaCategoriasString = new ArrayList<>();
        listaCategoriasString.add("Todos");

        try {
            listaCategorias = fCategoria.obtenerTodasLasCategorias();

            for (int i = 0; i < listaCategorias.size(); i++) {
                listaCategoriasString.add(listaCategorias.get(i).getNombre());
            }

            DefaultComboBoxModel<String> modelo = new DefaultComboBoxModel<>();

            for (String nombre : listaCategoriasString) {
                modelo.addElement(nombre);
            }

            cbCategorias.setModel(modelo);

        } catch (Exception ex) {
            Logger.getLogger(JPanelAdminProductosCRUD.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
    
    
    
    private void accionesConstantesGUI(){
        
        
        if(accion == ConstantesGUI.NUEVO){
            btnAccion.setText("Guardar");
        }
        
        if(accion == ConstantesGUI.EDITAR){
            btnAccion.setText("EDITAR");
        }
        
        if(accion == ConstantesGUI.ELIMINAR){
            btnAccion.setText("ELIMINAR");
            btnAccion.setBackground(Color.red);
        }
        
        
    }
    
    


    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jblAdminProductos = new javax.swing.JLabel();
        jScrollPaneProductos = new javax.swing.JScrollPane();
        jPanelExtrasProductos = new javax.swing.JPanel();
        txtDescripcionProducto = new javax.swing.JTextField();
        txtNombreProducto1 = new javax.swing.JTextField();
        jblCategoriaProducto = new javax.swing.JLabel();
        jblNombreProducto = new javax.swing.JLabel();
        jblDescripcionProducto1 = new javax.swing.JLabel();
        jSpinnerPrecioProducto = new javax.swing.JSpinner();
        cbCategorias = new javax.swing.JComboBox<>();
        jblExtraProducto = new javax.swing.JLabel();
        jblPrecioProducto = new javax.swing.JLabel();
        jPanelContenedorExtras = new javax.swing.JPanel();
        jPanelContenedorLeches = new javax.swing.JPanel();
        cbLeches = new javax.swing.JCheckBox();
        cbTipoExtras = new javax.swing.JCheckBox();
        jPanelContenedorVasos = new javax.swing.JPanel();
        jPanelContenedorTipoExtra = new javax.swing.JPanel();
        cbVasos = new javax.swing.JCheckBox();
        btnAccion = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(965, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(null);

        jblAdminProductos.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jblAdminProductos.setText("Agregar Producto");
        jPanel1.add(jblAdminProductos);
        jblAdminProductos.setBounds(20, 30, 170, 22);

        jScrollPaneProductos.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPaneProductos.setBorder(null);
        jScrollPaneProductos.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPaneProductos.setViewportView(jPanelExtrasProductos);

        jPanelExtrasProductos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelExtrasProductos.setMinimumSize(new java.awt.Dimension(965, 794));
        jPanelExtrasProductos.setPreferredSize(new java.awt.Dimension(965, 794));
        jPanelExtrasProductos.setLayout(null);

        txtDescripcionProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDescripcionProductoKeyTyped(evt);
            }
        });
        jPanelExtrasProductos.add(txtDescripcionProducto);
        txtDescripcionProducto.setBounds(10, 140, 770, 42);

        txtNombreProducto1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombreProducto1KeyTyped(evt);
            }
        });
        jPanelExtrasProductos.add(txtNombreProducto1);
        txtNombreProducto1.setBounds(10, 40, 770, 42);

        jblCategoriaProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblCategoriaProducto.setText("Categoria");
        jPanelExtrasProductos.add(jblCategoriaProducto);
        jblCategoriaProducto.setBounds(250, 230, 170, 22);

        jblNombreProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblNombreProducto.setText("Nombre del producto");
        jPanelExtrasProductos.add(jblNombreProducto);
        jblNombreProducto.setBounds(10, 10, 170, 22);

        jblDescripcionProducto1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblDescripcionProducto1.setText("Nombre del producto");
        jPanelExtrasProductos.add(jblDescripcionProducto1);
        jblDescripcionProducto1.setBounds(10, 110, 170, 22);
        jPanelExtrasProductos.add(jSpinnerPrecioProducto);
        jSpinnerPrecioProducto.setBounds(10, 260, 130, 40);

        cbCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Deshabilitado" }));
        cbCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCategoriasActionPerformed(evt);
            }
        });
        jPanelExtrasProductos.add(cbCategorias);
        cbCategorias.setBounds(250, 260, 150, 40);

        jblExtraProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblExtraProducto.setText("Extras");
        jPanelExtrasProductos.add(jblExtraProducto);
        jblExtraProducto.setBounds(10, 360, 170, 22);

        jblPrecioProducto.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jblPrecioProducto.setText("Precio");
        jPanelExtrasProductos.add(jblPrecioProducto);
        jblPrecioProducto.setBounds(10, 230, 170, 22);

        jPanelContenedorExtras.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedorExtras.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelContenedorExtras.setLayout(null);

        jPanelContenedorLeches.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedorLeches.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelContenedorExtras.add(jPanelContenedorLeches);
        jPanelContenedorLeches.setBounds(10, 210, 400, 80);

        cbLeches.setBackground(new java.awt.Color(255, 255, 255));
        cbLeches.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbLeches.setText("Leche");
        cbLeches.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbLechesActionPerformed(evt);
            }
        });
        jPanelContenedorExtras.add(cbLeches);
        cbLeches.setBounds(10, 180, 170, 20);

        cbTipoExtras.setBackground(new java.awt.Color(255, 255, 255));
        cbTipoExtras.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTipoExtras.setText("Extras");
        cbTipoExtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTipoExtrasActionPerformed(evt);
            }
        });
        jPanelContenedorExtras.add(cbTipoExtras);
        cbTipoExtras.setBounds(470, 30, 170, 20);

        jPanelContenedorVasos.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedorVasos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelContenedorExtras.add(jPanelContenedorVasos);
        jPanelContenedorVasos.setBounds(10, 60, 400, 80);

        jPanelContenedorTipoExtra.setBackground(new java.awt.Color(255, 255, 255));
        jPanelContenedorTipoExtra.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanelContenedorTipoExtra.setForeground(new java.awt.Color(204, 204, 204));
        jPanelContenedorExtras.add(jPanelContenedorTipoExtra);
        jPanelContenedorTipoExtra.setBounds(470, 60, 270, 290);

        cbVasos.setBackground(new java.awt.Color(255, 255, 255));
        cbVasos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbVasos.setText("Vasos");
        cbVasos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbVasosActionPerformed(evt);
            }
        });
        jPanelContenedorExtras.add(cbVasos);
        cbVasos.setBounds(10, 30, 170, 20);

        jPanelExtrasProductos.add(jPanelContenedorExtras);
        jPanelContenedorExtras.setBounds(10, 410, 780, 370);

        jScrollPaneProductos.setViewportView(jPanelExtrasProductos);

        jPanel1.add(jScrollPaneProductos);
        jScrollPaneProductos.setBounds(20, 70, 880, 500);

        btnAccion.setBackground(new java.awt.Color(17, 24, 39));
        btnAccion.setFont(new java.awt.Font("Helvetica Neue", 1, 16)); // NOI18N
        btnAccion.setForeground(new java.awt.Color(255, 255, 255));
        btnAccion.setText("Accion");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });
        jPanel1.add(btnAccion);
        btnAccion.setBounds(720, 30, 170, 30);

        add(jPanel1);
        jPanel1.setBounds(20, 14, 920, 590);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formMouseClicked

    private void txtDescripcionProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionProductoKeyTyped
        // TODO add your handling code here:


    }//GEN-LAST:event_txtDescripcionProductoKeyTyped

    private void txtNombreProducto1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreProducto1KeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProducto1KeyTyped

    private void cbCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCategoriasActionPerformed
        // TODO add your handling code here:}


    }//GEN-LAST:event_cbCategoriasActionPerformed

    private void cbLechesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbLechesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbLechesActionPerformed

    private void cbTipoExtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTipoExtrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTipoExtrasActionPerformed

    private void cbVasosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbVasosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbVasosActionPerformed

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btnAccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JComboBox<String> cbCategorias;
    private javax.swing.JCheckBox cbLeches;
    private javax.swing.JCheckBox cbTipoExtras;
    private javax.swing.JCheckBox cbVasos;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelContenedorExtras;
    private javax.swing.JPanel jPanelContenedorLeches;
    private javax.swing.JPanel jPanelContenedorTipoExtra;
    private javax.swing.JPanel jPanelContenedorVasos;
    private javax.swing.JPanel jPanelExtrasProductos;
    private javax.swing.JScrollPane jScrollPaneProductos;
    private javax.swing.JSpinner jSpinnerPrecioProducto;
    private javax.swing.JLabel jblAdminProductos;
    private javax.swing.JLabel jblCategoriaProducto;
    private javax.swing.JLabel jblDescripcionProducto1;
    private javax.swing.JLabel jblExtraProducto;
    private javax.swing.JLabel jblNombreProducto;
    private javax.swing.JLabel jblPrecioProducto;
    private javax.swing.JTextField txtDescripcionProducto;
    private javax.swing.JTextField txtNombreProducto1;
    // End of variables declaration//GEN-END:variables
}
