/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles;

import Entidades.Categoria;
import Entidades.Historialcorte;
import Entidades.Producto;
import Facades.IFachadaCategoriaControlador;
import Facades.IFachadaProductoControlador;
import Implementaciones.GestionarCategoriaControlador;
import Implementaciones.GestionarProductoControlador;
import JPA.HistorialcorteJpaController;
import java.awt.Color;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.RowFilter;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableRowSorter;
import utilerias.HintToTextField;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelAdminCortes extends javax.swing.JPanel {
    
    
    private final IFachadaCategoriaControlador fCategoria = new GestionarCategoriaControlador();
    private final IFachadaProductoControlador fProducto = new GestionarProductoControlador();
    
    private TableRowSorter<DefaultTableModel> sorter;
    
    Categoria categoriaUtil;
    List <Categoria> listaCategoriaUtil;
    Producto productoUtil;
    
    

    /**
     * Creates new form JPanelAdminCategorias
     */
    public JPanelAdminCortes() {
        initComponents();
        
        
        cargarDiseno();
        cargarHistorialCortes();
        
    }
    
    
    
  
    
    private void cargarDiseno(){
    
    }
    
    
    
    
    private void cargarHistorialCortes() {
        try {
            HistorialcorteJpaController ctrl = new HistorialcorteJpaController();
            List<Historialcorte> lista = ctrl.findHistorialcorteEntities();

            String[] columnas = {
                "ID Corte", "ID Caja", "Tipo Corte", "Monto Inicial",
                "Monto Final", "Diferencia", "Fecha y Hora"
            };

            DefaultTableModel model = new DefaultTableModel(columnas, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            for (Historialcorte h : lista) {
                Object[] fila = {
                    h.getId(),
                    h.getIdCaja(),
                    h.getTipoCorte(),
                    h.getMontoInicial(),
                    h.getMontoFinal(),
                    h.getDiferencia(),
                    h.getFechaHora()
                };
                model.addRow(fila);
            }

            tablaCortes.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al cargar historial: " + ex.getMessage());
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCortes = new javax.swing.JTable();
        jblAdminCortes = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(965, 620));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        setLayout(null);

        tablaCortes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCortes);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 90, 940, 510);

        jblAdminCortes.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jblAdminCortes.setText("Historial de cortes");
        add(jblAdminCortes);
        jblAdminCortes.setBounds(20, 30, 170, 22);
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:

        
        
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jblAdminCortes;
    private javax.swing.JTable tablaCortes;
    // End of variables declaration//GEN-END:variables
}
