/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles.elementos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;
import javax.swing.JPanel;
import utilerias.PanelRedondo;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelComandas extends javax.swing.JPanel {

    private int radius = 20;
    private boolean selecionado;
    
    /**
     * Creates new form JPanelComandas
     */
    public JPanelComandas() {
        initComponents();
        
        setOpaque(false); // importante para permitir bordes redondeados
        
        setRadiusPanelVerde();
    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        // Activar suavizado
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Color de fondo del panel
        g2.setColor(getBackground());

        // Rectángulo redondeado
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
        g2.setColor(Color.GRAY); // color del borde
        g2.setStroke(new BasicStroke(1)); // grosor
        g2.drawRoundRect(1, 1, getWidth()-2, getHeight()-2, radius, radius);

        g2.dispose();
        super.paintComponent(g);
    }

    // Si quieres cambiar el radio desde fuera:
    public void setRadius(int r) {
        this.radius = r;
        repaint();
    }
    
    

        /**
     * Establece el color de fondo del panel de estado a Color.GREEN 
     * y lo hace redondo usando la lógica de PanelRedondo.
     */
    public void setRadiusPanelVerde() {
        // 1. Establecer el color
            jPanelEstado.setBackground(Color.GREEN);

            // 2. Establecer el radio usando el cast a PanelRedondo
            if (jPanelEstado instanceof PanelRedondo) {
                ((PanelRedondo) jPanelEstado).setRadius(55); 
            }

            jPanelEstado.setOpaque(false);
            // 3. Forzar el redibujado de la clase que lo contiene.
            jPanelEstado.repaint();
            
    }
    
    
    
    
    public JLabel getJblNombreComanda() {
        return jblComandasActivas;
    }
    
    
    public JLabel getJblNumProductos() {
        return jblNumProductos;
    } 
    
    public JLabel getJblEliminarComanda() {
        return jblComandasEliminar;
    }
    
    public JLabel getJblPrecioProducto() {
        return jblPrecioProductos;
    } 
    
    public JPanel getJPanelEstado() {
        return jPanelEstado;
    } 

    public boolean isSelecionado() {
        return selecionado;
    }

    public void setSelecionado(boolean selecionado) {
        this.selecionado = selecionado;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblPrecioProductos = new javax.swing.JLabel();
        jblComandasActivas = new javax.swing.JLabel();
        jPanelEstado = new PanelRedondo();
        jblNumProductos = new javax.swing.JLabel();
        jblComandasEliminar = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(350, 90));
        setPreferredSize(new java.awt.Dimension(350, 90));
        setLayout(null);

        jblPrecioProductos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jblPrecioProductos.setForeground(new java.awt.Color(102, 102, 102));
        jblPrecioProductos.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblPrecioProductos.setText("$ 30.00");
        add(jblPrecioProductos);
        jblPrecioProductos.setBounds(240, 60, 90, 15);

        jblComandasActivas.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jblComandasActivas.setText("Comanda # 1 - 22/02/2025");
        add(jblComandasActivas);
        jblComandasActivas.setBounds(10, 15, 210, 15);

        jPanelEstado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelEstadoLayout = new javax.swing.GroupLayout(jPanelEstado);
        jPanelEstado.setLayout(jPanelEstadoLayout);
        jPanelEstadoLayout.setHorizontalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 31, Short.MAX_VALUE)
        );
        jPanelEstadoLayout.setVerticalGroup(
            jPanelEstadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        add(jPanelEstado);
        jPanelEstado.setBounds(250, 13, 31, 30);

        jblNumProductos.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jblNumProductos.setForeground(new java.awt.Color(102, 102, 102));
        jblNumProductos.setText("2 Productos");
        add(jblNumProductos);
        jblNumProductos.setBounds(10, 60, 150, 15);

        jblComandasEliminar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        jblComandasEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnEliminarProducto.png"))); // NOI18N
        jblComandasEliminar.setPreferredSize(new java.awt.Dimension(30, 30));
        add(jblComandasEliminar);
        jblComandasEliminar.setBounds(300, 10, 35, 35);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelEstado;
    private javax.swing.JLabel jblComandasActivas;
    private javax.swing.JLabel jblComandasEliminar;
    private javax.swing.JLabel jblNumProductos;
    private javax.swing.JLabel jblPrecioProductos;
    // End of variables declaration//GEN-END:variables
}
