/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles.elementos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelUsuario extends javax.swing.JPanel {

    
    private int radius = 20;
    
    /**
     * Creates new form JPanelProducto
     */
    public JPanelUsuario() {
        initComponents();
        
        setOpaque(false); // importante para permitir bordes redondeados

    }
    
    
    @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        // Activar suavizado
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Color de fondo del panel
        g2.setColor(getBackground());

        // Rectángulo redondeado
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
        g2.setColor(Color.GRAY); // color del borde
        g2.setStroke(new BasicStroke(1)); // grosor
        g2.drawRoundRect(1, 1, getWidth()-2, getHeight()-2, radius, radius);

        g2.dispose();
        super.paintComponent(g);
    }

    // Si quieres cambiar el radio desde fuera:
    public void setRadius(int r) {
        this.radius = r;
        repaint();
    }
    
    
    
    
    public JLabel getJblNombreUsuario() {
        return jblNombreUsuario;
    }
    
    public JLabel getJblNombreRol() {
        return jblNombreRol;
    }
    
    
    public JLabel getJblEliminarUsuario() {
        return jblEliminar;
    } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblEliminar = new javax.swing.JLabel();
        jblNombreRol = new javax.swing.JLabel();
        jblNombreUsuario = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(474, 62));
        setLayout(null);

        jblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnEliminarProducto.png"))); // NOI18N
        jblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jblEliminar);
        jblEliminar.setBounds(410, 10, 40, 40);

        jblNombreRol.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblNombreRol.setForeground(new java.awt.Color(51, 51, 255));
        jblNombreRol.setText("Rol");
        jblNombreRol.setAlignmentX(16.0F);
        jblNombreRol.setAlignmentY(0.0F);
        add(jblNombreRol);
        jblNombreRol.setBounds(20, 33, 180, 25);

        jblNombreUsuario.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblNombreUsuario.setForeground(new java.awt.Color(39, 24, 17));
        jblNombreUsuario.setText("Nombre Usuario");
        jblNombreUsuario.setAlignmentX(16.0F);
        jblNombreUsuario.setAlignmentY(0.0F);
        add(jblNombreUsuario);
        jblNombreUsuario.setBounds(20, 6, 180, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblEliminar;
    private javax.swing.JLabel jblNombreRol;
    private javax.swing.JLabel jblNombreUsuario;
    // End of variables declaration//GEN-END:variables
}
