/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles.elementos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelProducto extends javax.swing.JPanel {

    
    private int radius = 20;
    
    /**
     * Creates new form JPanelProducto
     */
    public JPanelProducto() {
        initComponents();
        
        setOpaque(false); // importante para permitir bordes redondeados

    }
    
    
     @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        // Activar suavizado
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Color de fondo del panel
        g2.setColor(getBackground());

        // Rectángulo redondeado
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
        g2.setColor(Color.GRAY); // color del borde
        g2.setStroke(new BasicStroke(1)); // grosor
        g2.drawRoundRect(1, 1, getWidth()-2, getHeight()-2, radius, radius);

        g2.dispose();
        super.paintComponent(g);
    }

    // Si quieres cambiar el radio desde fuera:
    public void setRadius(int r) {
        this.radius = r;
        repaint();
    }
    
    
    
    
    public JLabel getJblNombreProducto() {
        return jblNombreProducto;
    }
    
    public JLabel getJblNombreCategoria() {
        return jblNombreCategoria;
    }
    
    public JLabel getJblPrecioProducto() {
        return jblPrecioProducto;
    } 
    
    public JLabel getJblEliminarProducto() {
        return jblEliminar;
    } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblPrecioProducto = new javax.swing.JLabel();
        jblEliminar = new javax.swing.JLabel();
        jblNombreCategoria = new javax.swing.JLabel();
        jblNombreProducto = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(772, 62));
        setLayout(null);

        jblPrecioProducto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblPrecioProducto.setForeground(new java.awt.Color(39, 24, 17));
        jblPrecioProducto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblPrecioProducto.setText("Precio");
        jblPrecioProducto.setAlignmentX(16.0F);
        jblPrecioProducto.setAlignmentY(0.0F);
        add(jblPrecioProducto);
        jblPrecioProducto.setBounds(520, 17, 180, 30);

        jblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnEliminarProducto.png"))); // NOI18N
        jblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jblEliminar);
        jblEliminar.setBounds(722, 10, 40, 40);

        jblNombreCategoria.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblNombreCategoria.setForeground(new java.awt.Color(51, 153, 255));
        jblNombreCategoria.setText("Categoria");
        jblNombreCategoria.setAlignmentX(16.0F);
        jblNombreCategoria.setAlignmentY(0.0F);
        add(jblNombreCategoria);
        jblNombreCategoria.setBounds(20, 33, 180, 25);

        jblNombreProducto.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblNombreProducto.setForeground(new java.awt.Color(39, 24, 17));
        jblNombreProducto.setText("Nombre Producto");
        jblNombreProducto.setAlignmentX(16.0F);
        jblNombreProducto.setAlignmentY(0.0F);
        add(jblNombreProducto);
        jblNombreProducto.setBounds(20, 6, 180, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblEliminar;
    private javax.swing.JLabel jblNombreCategoria;
    private javax.swing.JLabel jblNombreProducto;
    private javax.swing.JLabel jblPrecioProducto;
    // End of variables declaration//GEN-END:variables
}
