/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Formularios.paneles.elementos;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JLabel;

/**
 *
 * @author Sergio Arturo
 */
public class JPanelExtra extends javax.swing.JPanel {

    
    private int radius = 20;
    
    /**
     * Creates new form JPanelProducto
     */
    public JPanelExtra() {
        initComponents();
        
        setOpaque(false); // importante para permitir bordes redondeados

    }
    
    
     @Override
    protected void paintComponent(Graphics g) {
        Graphics2D g2 = (Graphics2D) g.create();

        // Activar suavizado
        g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);

        // Color de fondo del panel
        g2.setColor(getBackground());

        // Rectángulo redondeado
        g2.fillRoundRect(0, 0, getWidth(), getHeight(), radius, radius);
        g2.setColor(Color.GRAY); // color del borde
        g2.setStroke(new BasicStroke(1)); // grosor
        g2.drawRoundRect(1, 1, getWidth()-2, getHeight()-2, radius, radius);

        g2.dispose();
        super.paintComponent(g);
    }

    // Si quieres cambiar el radio desde fuera:
    public void setRadius(int r) {
        this.radius = r;
        repaint();
    }
    
    
    
    
    public JLabel getJblNombreExtra() {
        return jblNombreExtra;
    }
    
    
    public JLabel getJblPrecioExtra() {
        return jblPrecioExtra;
    } 
    
    public JLabel getJblEliminarExtra() {
        return jblEliminar;
    } 
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jblPrecioExtra = new javax.swing.JLabel();
        jblEliminar = new javax.swing.JLabel();
        jblNombreExtra = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(530, 45));
        setLayout(null);

        jblPrecioExtra.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblPrecioExtra.setForeground(new java.awt.Color(39, 24, 17));
        jblPrecioExtra.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jblPrecioExtra.setText("Precio");
        jblPrecioExtra.setAlignmentX(16.0F);
        jblPrecioExtra.setAlignmentY(0.0F);
        add(jblPrecioExtra);
        jblPrecioExtra.setBounds(380, 10, 90, 30);

        jblEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/btnEliminarProducto.png"))); // NOI18N
        jblEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add(jblEliminar);
        jblEliminar.setBounds(480, 5, 40, 40);

        jblNombreExtra.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jblNombreExtra.setForeground(new java.awt.Color(39, 24, 17));
        jblNombreExtra.setText("Extra");
        jblNombreExtra.setAlignmentX(16.0F);
        jblNombreExtra.setAlignmentY(0.0F);
        add(jblNombreExtra);
        jblNombreExtra.setBounds(20, 10, 150, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jblEliminar;
    private javax.swing.JLabel jblNombreExtra;
    private javax.swing.JLabel jblPrecioExtra;
    // End of variables declaration//GEN-END:variables
}
